# Generated by Django 5.1.4 on 2025-03-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_add_problem_type_and_order'),
        ('problems', '0002_alter_problem_options_problem_order_and_more'),
    ]

    operations = [
    ]
