# Generated by Django 5.1.4 on 2025-04-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_merge_20250320_2316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_attempted',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='status',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_submitted', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
