# Generated by Django 5.1.4 on 2025-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(),
        ),
    ]
