name: algoai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.8.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - django=5.1.4
  - django-cors-headers=4.6.0
  - djangorestframework=3.15.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - libffi=3.4.2
  - liblzma=5.6.3
  - libsqlite=3.47.2
  - libzlib=1.3.1
  - openssl=3.4.0
  - pip=24.3.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.16
  - python_abi=3.10
  - requests=2.32.3
  - setuptools=75.6.0
  - sqlparse=0.5.3
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.3.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - djangorestframework-simplejwt==5.3.1
    - dotenv==0.9.9
    - flake8==7.1.1
    - mccabe==0.7.0
    - psycopg2==2.9.10
    - pycodestyle==2.12.1
    - pyflakes==3.2.0
    - pyjwt==2.10.1
    - python-dotenv==1.0.1 