# Generated by Django 5.1.4 on 2025-04-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_last_activity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_activity_date',
            new_name='last_solved_date',
        ),
    ]
