# Generated by Django 5.1.4 on 2025-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_estimated_completion_time_plan_learning_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='estimated_completion_time',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='learning_path',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='planproblem',
            name='notes',
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15),
        ),
    ]
