# Generated by Django 5.1.4 on 2025-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_plan_estimated_completion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
    ]
