# Generated by Django 5.1.4 on 2025-05-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_ai_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='topics',
            new_name='problem_types',
        ),
    ]
