# Generated by Django 5.1.4 on 2025-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_leaderboardentry_score_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='high_score',
            field=models.IntegerField(default=0),
        ),
    ]
