# Generated by Django 5.1.4 on 2025-04-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_leaderboardentry_high_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='high_score',
        ),
    ]
